apiVersion: v1
kind: Pod
spec:
  containers:
    - image: "jenkinsciinfra/builder:2.0.58"
      imagePullPolicy: "IfNotPresent"
      name: "jnlp"
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
        requests:
          memory: "512Mi"
          cpu: "1"
      securityContext:
        privileged: false
