# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'graphql-client'
gem 'httparty'
gem 'json'

gem "csv", "~> 3.3"

gem "logger", "~> 1.6"
