def cronExpr = env.BRANCH_IS_PRIMARY ? '@hourly' : ''
def reportMirrorbitsMirrorsList = env.BRANCH_IS_PRIMARY ? 'mirrorbits-mirrors-list.json' : "mirrorbits-mirrors-list-${env.BRANCH_NAME}.json"

pipeline {
  triggers {
    cron(cronExpr)
  }
  options {
    // This pipeline takes 1-2 minutes max to execute
    timeout(time: 10, unit: 'MINUTES')
    lock(resource: 'jenkins-infra-data', inversePrecedence: true)
    buildDiscarder logRotator(daysToKeepStr: '90')
  }
  agent {
    label 'jnlp-linux-arm64'
  }
  stages {
    stage('Generate Mirrorbits Mirrors List') {
      steps {
        dir('jenkins-infra-data') {
          sh "./mirrorbits-mirrors-list.sh > ${reportMirrorbitsMirrorsList}"
        }
      }
    }
    stage('Publish reports') {
      when {
        expression { env.BRANCH_IS_PRIMARY }
      }
      steps {
        dir('jenkins-infra-data') {
          publishReports ([reportMirrorbitsMirrorsList])
        }
      }
    }
  }
}
