# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'graphql'
gem 'httparty'
gem 'json'
gem 'openssl'
gem 'jwt'
gem 'time'
gem 'base64'
