def cronExpr = env.BRANCH_IS_PRIMARY ? 'H H/2 * * *' : ''
def reportName = env.BRANCH_IS_PRIMARY ? 'jira-users-report.json' : "jira-users-report-${env.BRANCH_NAME}.json"

pipeline {
  triggers {
    cron(cronExpr)
  }
  options {
    // This pipeline takes ~1.5 hour to run
    timeout(time: 2, unit: 'HOURS')
    lock(resource: 'infra-reports-jira-users', inversePrecedence: true)
  }
  agent {
    kubernetes {
      yamlFile 'JenkinsAgentPodTemplate.yaml'
    }
  }
  stages {
    stage('Generate JIRA Users Report') {
      environment {
        JIRA_AUTH = credentials('jiraAuth')
        REPORT_NAME = "${reportName}"
      }
      steps {
        dir('jira-users-report') {
          sh 'bash ./user-report.sh > "${REPORT_NAME}"'
          archiveArtifacts reportName
        }
      }
    }
    stage('Publish JIRA Users Report') {
      when {
        expression { env.BRANCH_IS_PRIMARY }
      }
      steps {
        dir('jira-users-report') {
          publishReports ([reportName])
        }
      }
    }
  }
}
